services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=patch_advisor
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 6000:5432
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
